plugins {
    id "fabric-loom"
}

version = ""

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

base {
    archivesName = "${rootProject.archives_base_name}-${rootProject.mod_version}+mc${project.minecraft_version}"
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation project(":common")
    include project(":common")
}

processResources {
    inputs.property "version", project.mod_version
    inputs.property "minecraft_version", project.minecraft_version

    filesMatching("fabric.mod.json") {
        expand "version": project.mod_version, "minecraft_version": project.minecraft_version
    }
}
